# Log4j2 properties configuration

property.LOG_DIR = logs
property.ARCHIVE_LOG_DIR = ${LOG_DIR}/archive
property.pattern_file = %d{HH:mm:ss.SSS} [%t] %-5level %logger{5} - %msg%n

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %r %-5level %logger{3} - %msg%n

appender.rolling.type = RollingFile
appender.rolling.name = FileRolling
appender.rolling.fileName = ${LOG_DIR}/text_log.log
appender.rolling.filePattern = ${LOG_DIR}/${date:yyyy-MM-dd}/%d{yyyy-MM-dd_HH-mm}_%i.log
appender.rolling.append = true
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = ${pattern_file}
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 1KB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 10

logger.Log_Console.name = Log_Console
logger.Log_Console.level = debug
logger.Log_Console.additivity = true
logger.Log_Console.appenderRef.console.ref = Console

logger.Rolling_File.name = Rolling_File
logger.Rolling_File.level = debug
logger.Rolling_File.additivity = false
logger.Rolling_File.appenderRef.rolling.ref = FileRolling

rootLogger.level = all
rootLogger.appenderRef.rolling.ref = FileRolling
rootLogger.appenderRef.console.ref = Console